---
ocean:
  version: "1"
images:
  - name: ray
    registry: docker_hub
    image: getocean/ray-notebook
    tag: latest
    snapshottable: true
steps:
  - engines:
      - name: ray_jupyter
        vars:
          - name: ray_head_host
            value: "{{ engines.ray_jupyter.deployment.nodes.main.private_ip }}"
          - name: ray_head_port
            value: "{% reserve_private_port %}"
          - name: ray_dashboard_port
            value: "{% reserve_public_port %}"
          - name: ray_node_manager_port
            value: "{% reserve_private_port %}"
          - name: ray_object_manager_port
            value: "{% reserve_private_port %}"
          - name: gcs_server_port
            value: "{% reserve_private_port %}"
          - name: jupyter_port
            value: "{% reserve_public_port %}"
          - name: jupyter_token
            value: "{% generate_uuid %}"
        deployment:
          strategy: main
        container:
          image_name: ray
          user: root
          workdir: /work
          mounts:
            app_files:
              - name: ray_jupyter
                app_files_path: ray_jupyter
                container_path: /ocean/etc/ray_jupyter
                readonly: true
            data_stores: "{{ engines.ray_jupyter.container.workdir }}"
          command: "{{ engines.ray_jupyter.container.mounts.app_files.ray_jupyter.container_path }}/startup.sh"
          env_vars:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: NB_UID
              value: "{{ workspace.user.uid }}"
            - name: NB_GID
              value: "{{ workspace.user.gid }}"
            - name: CHOWN_HOME
              value: "yes"
            - name: GRANT_SUDO
              value: "yes"
            - name: RESTARTABLE
              value: "yes"
            - name: RAY_ADDRESS
              value: "{{ engines.ray_jupyter.vars.ray_head_host }}:{{ engines.ray_jupyter.vars.ray_head_port }}"
        ui:
          buttons:
            - label: Ray Dashboard
              url: "http://{{ engines.ray_jupyter.ui.buttons.self.node.public_ip }}:{{ engines.ray_jupyter.vars.ray_dashboard_port }}"
            - label: Jupyter Notebook
              url: "http://{{ engines.ray_jupyter.ui.buttons.self.node.public_ip }}:{{ engines.ray_jupyter.vars.jupyter_port }}?token={{ engines.ray_jupyter.vars.jupyter_token }}"
  - engines:
      - name: ray_worker
        vars:
          - name: ray_node_manager_port
            value: "{% reserve_private_port %}"
          - name: ray_object_manager_port
            value: "{% reserve_private_port %}"
          - name: gcs_server_port
            value: "{% reserve_private_port %}"
        deployment:
          strategy: workers_fill_pool_if_available
        container:
          image_name: ray
          user: root
          workdir: /work
          mounts:
            app_files:
              - name: ray_worker
                app_files_path: ray_worker
                container_path: /ocean/etc/ray_worker
                readonly: true
            data_stores: "{{ engines.ray_worker.container.workdir }}"
          command: "{{ engines.ray_worker.container.mounts.app_files.ray_worker.container_path }}/startup.sh"
          env_vars:
            - name: NB_UID
              value: "{{ workspace.user.uid }}"
            - name: NB_GID
              value: "{{ workspace.user.gid }}"
            - name: CHOWN_HOME
              value: 'yes'